import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Colors, Fonts, Spacing, BorderRadius } from '@/theme';
import { AppHeader } from '@/components/Header';
import Icon from '@/components/Icon';
import { ChatThread, useKeyboardScrollNudge } from '@/components/ChatThread';
import { useChatSession } from '@/hooks/useChatSession';
import { useAuthStore } from '@/store/authStore';
import { GuestGate } from '@/components/GuestGate';
import { doctorService, type AyurvedicDoctor } from '@/services/doctorService';

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildSummaryHtml(doctor: AyurvedicDoctor, exchanges: { question: string; answer: string }[]): string {
  const generatedAt = new Date().toLocaleString();
  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1c1c15; padding: 32px; }
  h1 { color: #002410; font-size: 20px; margin-bottom: 2px; }
  .subtitle { color: #717971; font-size: 12px; margin-bottom: 16px; }
  .disclaimer { background: #fdecea; border: 1px solid #f3c2bb; border-radius: 8px; padding: 12px 14px; font-size: 12px; color: #7a271a; margin-bottom: 20px; line-height: 1.5; }
  .clinic { background: #f0f4ee; border-radius: 8px; padding: 12px 14px; font-size: 13px; margin-bottom: 20px; }
  .clinic .label { font-weight: 600; color: #002410; }
  h2 { color: #002410; font-size: 14px; border-bottom: 1px solid #c1c9bf; padding-bottom: 4px; margin-top: 20px; }
  .q { font-weight: 600; font-size: 13px; margin-top: 12px; }
  .a { font-size: 13px; margin-top: 4px; line-height: 1.5; }
</style>
</head>
<body>
  <h1>AI Wellness Consultation Summary</h1>
  <div class="subtitle">Generated ${escapeHtml(generatedAt)}</div>

  <div class="disclaimer">
    This summary was generated by AyurTrace+'s AI assistant. It is <strong>not a medical
    prescription</strong> and has not been written, reviewed, or endorsed by ${escapeHtml(doctor.doctorName)}
    or ${escapeHtml(doctor.clinicHospitalName || 'the clinic listed below')}. For an official diagnosis
    or prescription, please contact the clinic directly.
  </div>

  <div class="clinic">
    <div><span class="label">Suggested contact:</span> ${escapeHtml(doctor.doctorName)}${doctor.qualification ? ` (${escapeHtml(doctor.qualification)})` : ''}</div>
    ${doctor.clinicHospitalName ? `<div>${escapeHtml(doctor.clinicHospitalName)}</div>` : ''}
    ${doctor.registeredAddress ? `<div>${escapeHtml(doctor.registeredAddress)}</div>` : ''}
  </div>

  <h2>Conversation Summary</h2>
  ${exchanges
    .map((e) => `<div class="q">Q: ${escapeHtml(e.question)}</div><div class="a">${escapeHtml(e.answer)}</div>`)
    .join('')}
</body>
</html>`;
}

export default function DoctorConsultScreen() {
  const router = useRouter();
  const { doctorId } = useLocalSearchParams<{ doctorId: string }>();
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const isGuest = useAuthStore((s) => s.isGuest);
  const canChat = isAuthenticated && !isGuest;

  const [doctor, setDoctor] = useState<AyurvedicDoctor | null>(null);
  const [doctorLoading, setDoctorLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const result = await doctorService.getById(doctorId);
        setDoctor(result);
      } finally {
        setDoctorLoading(false);
      }
    })();
  }, [doctorId]);

  const chat = useChatSession(canChat);
  useKeyboardScrollNudge(chat.scrollRef, [chat.messages, chat.sending]);

  const [generatingPdf, setGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);

  const exchanges: { question: string; answer: string }[] = [];
  for (let i = 0; i < chat.messages.length - 1; i++) {
    if (chat.messages[i].role === 'user' && chat.messages[i + 1].role === 'assistant') {
      exchanges.push({ question: chat.messages[i].content, answer: chat.messages[i + 1].content });
    }
  }

  async function handleGenerateSummary() {
    if (!doctor) return;
    setGeneratingPdf(true);
    setPdfError(null);
    try {
      const html = buildSummaryHtml(doctor, exchanges);
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'AI Wellness Consultation Summary' });
      } else {
        setPdfError('Sharing is not available on this device — the PDF was generated but could not be saved.');
      }
    } catch (err) {
      setPdfError(`Could not generate the summary: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setGeneratingPdf(false);
    }
  }

  const headerTitle = doctor
    ? `Consult · ${doctor.clinicHospitalName || doctor.doctorName}`
    : 'Consult a Doctor';

  return (
    <SafeAreaView style={styles.container}>
      <AppHeader showBack onBackPress={() => router.back()} title={headerTitle} />

      {doctorLoading ? (
        <View style={styles.centerBox}>
          <ActivityIndicator color={Colors.primary} />
        </View>
      ) : !doctor ? (
        <View style={styles.centerBox}>
          <Text style={styles.errorText}>Doctor not found.</Text>
        </View>
      ) : (
        <GuestGate message="Sign in to start a consultation.">
          <View style={styles.doctorStrip}>
            <View style={styles.doctorIconBox}>
              <Icon name="medkit-outline" size={18} color={Colors.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.doctorName} numberOfLines={1}>{doctor.doctorName}</Text>
              <Text style={styles.doctorMeta} numberOfLines={1}>
                {[doctor.qualification, doctor.district].filter(Boolean).join(' · ')}
              </Text>
            </View>
            {exchanges.length > 0 && (
              <TouchableOpacity style={styles.summaryBtn} onPress={handleGenerateSummary} disabled={generatingPdf}>
                {generatingPdf ? (
                  <ActivityIndicator size="small" color={Colors.onPrimary} />
                ) : (
                  <Icon name="document-text-outline" size={16} color={Colors.onPrimary} />
                )}
              </TouchableOpacity>
            )}
          </View>
          {pdfError && (
            <View style={styles.pdfErrorBox}>
              <Text style={styles.pdfErrorText}>{pdfError}</Text>
            </View>
          )}

          <ChatThread
            {...chat}
            greeting={`Hello! I'm here to help with your wellness questions. ${doctor.clinicHospitalName || doctor.doctorName} is shown as a suggested local contact — my answers are AI-generated, not written by them.`}
            disclaimer="This consultation uses AyurTrace+'s AI. It never diagnoses or replaces professional medical advice — the doctor/clinic shown is a suggested contact, not the author of these replies."
          />
        </GuestGate>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  centerBox: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  errorText: { fontFamily: Fonts.family.regular, fontSize: Fonts.size.sm, color: Colors.textMuted },
  doctorStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.gutter,
    paddingVertical: Spacing.sm,
    backgroundColor: Colors.surfaceContainerLowest,
    borderBottomWidth: 1,
    borderBottomColor: Colors.outlineVariant,
  },
  doctorIconBox: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doctorName: { fontFamily: Fonts.family.semiBold, fontSize: Fonts.size.sm, color: Colors.onSurface },
  doctorMeta: { fontFamily: Fonts.family.regular, fontSize: 11, color: Colors.textMuted, marginTop: 1 },
  summaryBtn: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pdfErrorBox: {
    paddingHorizontal: Spacing.gutter,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.errorContainer,
  },
  pdfErrorText: { fontFamily: Fonts.family.regular, fontSize: 11, color: Colors.onErrorContainer },
});
