-- ============================================================================
-- AyurTrace+ — set login passwords for all 40 member accounts
--
-- WHERE: Supabase Dashboard → SQL Editor → New query → paste → Run.
-- The SQL Editor runs as a superuser, so it can write to auth.users directly.
-- No service_role key and no password-reset emails are required.
--
-- Passwords are bcrypt-hashed by pgcrypto and stored in auth.users, where
-- Supabase Auth expects them. Nothing is written to public.members, and no
-- plaintext password is stored anywhere in the database.
--
-- Safe to re-run: it re-applies the same passwords.
--
-- GENERATED by scripts/generate_member_passwords.py — do not hand-edit.
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;

-- The credential set is inlined as a CTE in each statement rather than held in
-- a temp table, purely so the SQL Editor's "table without RLS" linter stays
-- quiet. Nothing here creates a persistent object.

-- ── 1. Create any auth user that doesn't exist yet ──────────────────────────
-- Members registered via the "123456" demo bypass never reached Supabase Auth.
-- Existing accounts are left untouched.
with creds(email, password) as (values
    ('koushikiam18@gmail.com', 'Demo@CC01'),
    ('kanikarthi399@gmail.com', 'Demo@CC02'),
    ('karthiga.cse2024@citchennai.net', 'Demo@CC03'),
    ('pranatheeshs@gmail.com', 'Demo@CC04'),
    ('pranatheeshs.aiml2024@citchennai.net', 'Demo@CC05'),
    ('mohanachandran2007@gmail.com', 'Demo@FR01'),
    ('sridhars.vlsi2024@citchennai.net', 'Demo@FR02'),
    ('ss.sridhar05@gmail.com', 'Demo@FR03'),
    ('nithinceetee.1@gmail.com', 'Demo@FR04'),
    ('mnithinchinnathambi.cse2024@citchennai.net', 'Demo@FR05'),
    ('sakash.cse2024@citchennai.net', 'Demo@FR06'),
    ('lavanya.g29122006@gmail.com', 'Demo@FR07'),
    ('lavanyag.cse2024@citchennai.net', 'Demo@FR08'),
    ('athiraithenral2007@gmail.com', 'Demo@FR09'),
    ('128010011@sastra.ac.in', 'Demo@FR10'),
    ('koushikpalanisamy45@gmail.com', 'Demo@MF01'),
    ('vsachinkumaran.cse2024@citchennai.net', 'Demo@MF02'),
    ('krssellamuthu2007@gmail.com', 'Demo@MF03'),
    ('sellamuthur.cse2024@citchennai.net', 'Demo@MF04'),
    ('sellamuthu14363@gmail.com', 'Demo@MF05'),
    ('pcm01032007@gmail.com', 'Demo@PL01'),
    ('kiruthikroshant.cse2024@citchennai.net', 'Demo@PL02'),
    ('rohiths.ece2024@citchennai.net', 'Demo@PL03'),
    ('logeshwaran0630@gmail.com', 'Demo@PL04'),
    ('logeshwaranj.cse2024@citchennai.net', 'Demo@PL05'),
    ('senthamizhselvan.sm@gmail.com', 'Demo@SC01'),
    ('kirunith2007@gmail.com', 'Demo@SC02'),
    ('kirunithrayane.cse2024@citchennai.net', 'Demo@SC03'),
    ('jainaakarthi840@gmail.com', 'Demo@SC04'),
    ('jsshakkeerjamalmd.aids2024@citchennai.net', 'Demo@SC05'),
    ('mohanachandhiranp.ece2024@citchennai.net', 'Demo@WC01'),
    ('nanchilakashkumar@gmail.com', 'Demo@WC02'),
    ('24f2007139@ds.study.iitm.ac.in', 'Demo@WC03'),
    ('pranatheesh@gmail.com', 'Demo@WC04'),
    ('rockstarrohith06@gmail.com', 'Demo@WC05'),
    ('tharunm.cse2024@citchennai.net', 'Demo@WC06'),
    ('tharunjanani33@gmail.com', 'Demo@WC07'),
    ('rockstarohith06@gmail.com', 'Demo@WC08'),
    ('schnkumaran429@gmail.com', 'Demo@WC09'),
    ('keshiy26@gmail.com', 'Demo@WC10')
)
-- confirmed_at is deliberately absent: Supabase defines it as a generated column
-- (least of email_confirmed_at / phone_confirmed_at), so writing it errors.
insert into auth.users (
  id, instance_id, aud, role, email,
  encrypted_password, email_confirmed_at,
  created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data,
  is_sso_user, is_anonymous
)
select
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated', 'authenticated',
  c.email,
  extensions.crypt(c.password, extensions.gen_salt('bf')),
  now(), now(), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{}'::jsonb,
  false, false
from creds c
where not exists (
  select 1 from auth.users u where lower(u.email) = c.email
);

-- ── 2. Set the password and confirm the email ───────────────────────────────
-- email_confirmed_at matters because this project requires confirmation;
-- without it sign-in fails with "Email not confirmed" despite a valid password.
with creds(email, password) as (values
    ('koushikiam18@gmail.com', 'Demo@CC01'),
    ('kanikarthi399@gmail.com', 'Demo@CC02'),
    ('karthiga.cse2024@citchennai.net', 'Demo@CC03'),
    ('pranatheeshs@gmail.com', 'Demo@CC04'),
    ('pranatheeshs.aiml2024@citchennai.net', 'Demo@CC05'),
    ('mohanachandran2007@gmail.com', 'Demo@FR01'),
    ('sridhars.vlsi2024@citchennai.net', 'Demo@FR02'),
    ('ss.sridhar05@gmail.com', 'Demo@FR03'),
    ('nithinceetee.1@gmail.com', 'Demo@FR04'),
    ('mnithinchinnathambi.cse2024@citchennai.net', 'Demo@FR05'),
    ('sakash.cse2024@citchennai.net', 'Demo@FR06'),
    ('lavanya.g29122006@gmail.com', 'Demo@FR07'),
    ('lavanyag.cse2024@citchennai.net', 'Demo@FR08'),
    ('athiraithenral2007@gmail.com', 'Demo@FR09'),
    ('128010011@sastra.ac.in', 'Demo@FR10'),
    ('koushikpalanisamy45@gmail.com', 'Demo@MF01'),
    ('vsachinkumaran.cse2024@citchennai.net', 'Demo@MF02'),
    ('krssellamuthu2007@gmail.com', 'Demo@MF03'),
    ('sellamuthur.cse2024@citchennai.net', 'Demo@MF04'),
    ('sellamuthu14363@gmail.com', 'Demo@MF05'),
    ('pcm01032007@gmail.com', 'Demo@PL01'),
    ('kiruthikroshant.cse2024@citchennai.net', 'Demo@PL02'),
    ('rohiths.ece2024@citchennai.net', 'Demo@PL03'),
    ('logeshwaran0630@gmail.com', 'Demo@PL04'),
    ('logeshwaranj.cse2024@citchennai.net', 'Demo@PL05'),
    ('senthamizhselvan.sm@gmail.com', 'Demo@SC01'),
    ('kirunith2007@gmail.com', 'Demo@SC02'),
    ('kirunithrayane.cse2024@citchennai.net', 'Demo@SC03'),
    ('jainaakarthi840@gmail.com', 'Demo@SC04'),
    ('jsshakkeerjamalmd.aids2024@citchennai.net', 'Demo@SC05'),
    ('mohanachandhiranp.ece2024@citchennai.net', 'Demo@WC01'),
    ('nanchilakashkumar@gmail.com', 'Demo@WC02'),
    ('24f2007139@ds.study.iitm.ac.in', 'Demo@WC03'),
    ('pranatheesh@gmail.com', 'Demo@WC04'),
    ('rockstarrohith06@gmail.com', 'Demo@WC05'),
    ('tharunm.cse2024@citchennai.net', 'Demo@WC06'),
    ('tharunjanani33@gmail.com', 'Demo@WC07'),
    ('rockstarohith06@gmail.com', 'Demo@WC08'),
    ('schnkumaran429@gmail.com', 'Demo@WC09'),
    ('keshiy26@gmail.com', 'Demo@WC10')
)
update auth.users u
set
  encrypted_password = extensions.crypt(c.password, extensions.gen_salt('bf')),
  -- Setting email_confirmed_at is enough; confirmed_at derives from it.
  email_confirmed_at = coalesce(u.email_confirmed_at, now()),
  updated_at         = now()
from creds c
where lower(u.email) = c.email;

-- ── 3. Backfill the email identity ──────────────────────────────────────────
-- Password sign-in requires an 'email' identity row.
insert into auth.identities (
  id, user_id, identity_data, provider, provider_id,
  last_sign_in_at, created_at, updated_at
)
select
  gen_random_uuid(), u.id,
  jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true),
  'email', u.id::text,
  now(), now(), now()
from auth.users u
where lower(u.email) in (
  'koushikiam18@gmail.com',
  'kanikarthi399@gmail.com',
  'karthiga.cse2024@citchennai.net',
  'pranatheeshs@gmail.com',
  'pranatheeshs.aiml2024@citchennai.net',
  'mohanachandran2007@gmail.com',
  'sridhars.vlsi2024@citchennai.net',
  'ss.sridhar05@gmail.com',
  'nithinceetee.1@gmail.com',
  'mnithinchinnathambi.cse2024@citchennai.net',
  'sakash.cse2024@citchennai.net',
  'lavanya.g29122006@gmail.com',
  'lavanyag.cse2024@citchennai.net',
  'athiraithenral2007@gmail.com',
  '128010011@sastra.ac.in',
  'koushikpalanisamy45@gmail.com',
  'vsachinkumaran.cse2024@citchennai.net',
  'krssellamuthu2007@gmail.com',
  'sellamuthur.cse2024@citchennai.net',
  'sellamuthu14363@gmail.com',
  'pcm01032007@gmail.com',
  'kiruthikroshant.cse2024@citchennai.net',
  'rohiths.ece2024@citchennai.net',
  'logeshwaran0630@gmail.com',
  'logeshwaranj.cse2024@citchennai.net',
  'senthamizhselvan.sm@gmail.com',
  'kirunith2007@gmail.com',
  'kirunithrayane.cse2024@citchennai.net',
  'jainaakarthi840@gmail.com',
  'jsshakkeerjamalmd.aids2024@citchennai.net',
  'mohanachandhiranp.ece2024@citchennai.net',
  'nanchilakashkumar@gmail.com',
  '24f2007139@ds.study.iitm.ac.in',
  'pranatheesh@gmail.com',
  'rockstarrohith06@gmail.com',
  'tharunm.cse2024@citchennai.net',
  'tharunjanani33@gmail.com',
  'rockstarohith06@gmail.com',
  'schnkumaran429@gmail.com',
  'keshiy26@gmail.com'
)
and not exists (
  select 1 from auth.identities i
  where i.user_id = u.id and i.provider = 'email'
);

-- ── 4. Verification ─────────────────────────────────────────────────────────
-- Every row should read true / true / true. member_status shows who may
-- actually sign in: Pending and Suspended accounts are blocked by the app's
-- login gate until an admin approves them.
select
  m."ayurvedicId",
  m.role,
  u.email,
  (u.encrypted_password is not null and u.encrypted_password <> '') as password_set,
  (u.email_confirmed_at is not null)                                as email_confirmed,
  exists (
    select 1 from auth.identities i
    where i.user_id = u.id and i.provider = 'email'
  )                                                                  as has_email_identity,
  m.status                                                           as member_status
from auth.users u
join public.members m on lower(m.email) = lower(u.email)
where lower(u.email) in (
  'koushikiam18@gmail.com',
  'kanikarthi399@gmail.com',
  'karthiga.cse2024@citchennai.net',
  'pranatheeshs@gmail.com',
  'pranatheeshs.aiml2024@citchennai.net',
  'mohanachandran2007@gmail.com',
  'sridhars.vlsi2024@citchennai.net',
  'ss.sridhar05@gmail.com',
  'nithinceetee.1@gmail.com',
  'mnithinchinnathambi.cse2024@citchennai.net',
  'sakash.cse2024@citchennai.net',
  'lavanya.g29122006@gmail.com',
  'lavanyag.cse2024@citchennai.net',
  'athiraithenral2007@gmail.com',
  '128010011@sastra.ac.in',
  'koushikpalanisamy45@gmail.com',
  'vsachinkumaran.cse2024@citchennai.net',
  'krssellamuthu2007@gmail.com',
  'sellamuthur.cse2024@citchennai.net',
  'sellamuthu14363@gmail.com',
  'pcm01032007@gmail.com',
  'kiruthikroshant.cse2024@citchennai.net',
  'rohiths.ece2024@citchennai.net',
  'logeshwaran0630@gmail.com',
  'logeshwaranj.cse2024@citchennai.net',
  'senthamizhselvan.sm@gmail.com',
  'kirunith2007@gmail.com',
  'kirunithrayane.cse2024@citchennai.net',
  'jainaakarthi840@gmail.com',
  'jsshakkeerjamalmd.aids2024@citchennai.net',
  'mohanachandhiranp.ece2024@citchennai.net',
  'nanchilakashkumar@gmail.com',
  '24f2007139@ds.study.iitm.ac.in',
  'pranatheesh@gmail.com',
  'rockstarrohith06@gmail.com',
  'tharunm.cse2024@citchennai.net',
  'tharunjanani33@gmail.com',
  'rockstarohith06@gmail.com',
  'schnkumaran429@gmail.com',
  'keshiy26@gmail.com'
)
order by m.role, m."ayurvedicId";
