"""
Generates login passwords for every member and emits:

  sql/set_all_member_passwords.sql  — paste into the Supabase SQL Editor
  CREDENTIALS.md                    — the human-readable credential table

Reads members_raw.json (a dump of public.members). Deterministic: re-running
with the same input produces the same passwords.

  python scripts/generate_member_passwords.py
"""

import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Password prefix per role. Numbering follows registration order.
ROLE_PREFIX = {
    "Collection Center": "CC",
    "Farmer": "FR",
    "Wild Collector": "WC",
    "Processing & Laboratory": "PL",
    "Manufacturer": "MF",
    "Supply Chain": "SC",
    "Government": "GV",
}

# Collection Centre passwords are pinned to the admin's existing spreadsheet so
# the credentials already circulated stay valid.
PINNED = {
    "koushikiam18@gmail.com": "Demo@CC01",
    "kanikarthi399@gmail.com": "Demo@CC02",
    "karthiga.cse2024@citchennai.net": "Demo@CC03",
    "pranatheeshs@gmail.com": "Demo@CC04",
    "pranatheeshs.aiml2024@citchennai.net": "Demo@CC05",
}


def sql_quote(value: str) -> str:
    """Single-quoted SQL literal with embedded quotes escaped."""
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    members = json.loads((ROOT / "members_raw.json").read_text(encoding="utf-8"))

    for m in members:
        m["_email"] = (m.get("email") or "").strip().lower()

    # ── Resolve duplicate emails ────────────────────────────────────────────
    # auth.users.email is UNIQUE, so only one member per address can hold a
    # login. Prefer an Active row; otherwise the earliest registration.
    by_email: dict[str, list[dict]] = defaultdict(list)
    for m in members:
        by_email[m["_email"]].append(m)

    # Prefer the row most likely to need a working login: Active now, Pending
    # once approved; Suspended last, since it can never sign in.
    status_rank = {"Active": 0, "Pending": 1, "Suspended": 2}

    winners, skipped = [], []
    for email, rows in by_email.items():
        if len(rows) == 1:
            winners.append(rows[0])
            continue
        rows_sorted = sorted(
            rows,
            key=lambda r: (status_rank.get(r["status"], 3), r.get("registeredDate") or ""),
        )
        winners.append(rows_sorted[0])
        for loser in rows_sorted[1:]:
            loser["_reason"] = f"email already used by {rows_sorted[0]['ayurvedicId']}"
            skipped.append(loser)

    # ── Assign passwords ────────────────────────────────────────────────────
    winners.sort(key=lambda m: (m["role"], m.get("registeredDate") or ""))
    counters: dict[str, int] = defaultdict(int)

    for m in winners:
        if m["_email"] in PINNED:
            m["_password"] = PINNED[m["_email"]]
            counters[m["role"]] = max(
                counters[m["role"]],
                int(re.search(r"(\d+)$", PINNED[m["_email"]]).group(1)),
            )
            continue
        prefix = ROLE_PREFIX.get(m["role"], "XX")
        counters[m["role"]] += 1
        m["_password"] = f"Demo@{prefix}{counters[m['role']]:02d}"

    # A duplicate password would silently overwrite another account's login.
    passwords = [m["_password"] for m in winners]
    assert len(passwords) == len(set(passwords)), "duplicate password generated"

    # ── Emit SQL ────────────────────────────────────────────────────────────
    values = ",\n".join(
        f"    ({sql_quote(m['_email'])}, {sql_quote(m['_password'])})" for m in winners
    )
    email_list = ",\n  ".join(sql_quote(m["_email"]) for m in winners)

    sql = f"""-- ============================================================================
-- AyurTrace+ — set login passwords for all {len(winners)} member accounts
--
-- WHERE: Supabase Dashboard → SQL Editor → New query → paste → Run.
-- The SQL Editor runs as a superuser, so it can write to auth.users directly.
-- No service_role key and no password-reset emails are required.
--
-- Passwords are bcrypt-hashed by pgcrypto and stored in auth.users, where
-- Supabase Auth expects them. Nothing is written to public.members, and no
-- plaintext password is stored anywhere in the database.
--
-- Safe to re-run: it re-applies the same passwords.
--
-- GENERATED by scripts/generate_member_passwords.py — do not hand-edit.
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;

-- The credential set is inlined as a CTE in each statement rather than held in
-- a temp table, purely so the SQL Editor's "table without RLS" linter stays
-- quiet. Nothing here creates a persistent object.

-- ── 1. Create any auth user that doesn't exist yet ──────────────────────────
-- Members registered via the "123456" demo bypass never reached Supabase Auth.
-- Existing accounts are left untouched.
with creds(email, password) as (values
{values}
)
-- confirmed_at is deliberately absent: Supabase defines it as a generated column
-- (least of email_confirmed_at / phone_confirmed_at), so writing it errors.
insert into auth.users (
  id, instance_id, aud, role, email,
  encrypted_password, email_confirmed_at,
  created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data,
  is_sso_user, is_anonymous
)
select
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated', 'authenticated',
  c.email,
  extensions.crypt(c.password, extensions.gen_salt('bf')),
  now(), now(), now(),
  '{{"provider":"email","providers":["email"]}}'::jsonb,
  '{{}}'::jsonb,
  false, false
from creds c
where not exists (
  select 1 from auth.users u where lower(u.email) = c.email
);

-- ── 2. Set the password and confirm the email ───────────────────────────────
-- email_confirmed_at matters because this project requires confirmation;
-- without it sign-in fails with "Email not confirmed" despite a valid password.
with creds(email, password) as (values
{values}
)
update auth.users u
set
  encrypted_password = extensions.crypt(c.password, extensions.gen_salt('bf')),
  -- Setting email_confirmed_at is enough; confirmed_at derives from it.
  email_confirmed_at = coalesce(u.email_confirmed_at, now()),
  updated_at         = now()
from creds c
where lower(u.email) = c.email;

-- ── 3. Backfill the email identity ──────────────────────────────────────────
-- Password sign-in requires an 'email' identity row.
insert into auth.identities (
  id, user_id, identity_data, provider, provider_id,
  last_sign_in_at, created_at, updated_at
)
select
  gen_random_uuid(), u.id,
  jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true),
  'email', u.id::text,
  now(), now(), now()
from auth.users u
where lower(u.email) in (
  {email_list}
)
and not exists (
  select 1 from auth.identities i
  where i.user_id = u.id and i.provider = 'email'
);

-- ── 4. Verification ─────────────────────────────────────────────────────────
-- Every row should read true / true / true. member_status shows who may
-- actually sign in: Pending and Suspended accounts are blocked by the app's
-- login gate until an admin approves them.
select
  m."ayurvedicId",
  m.role,
  u.email,
  (u.encrypted_password is not null and u.encrypted_password <> '') as password_set,
  (u.email_confirmed_at is not null)                                as email_confirmed,
  exists (
    select 1 from auth.identities i
    where i.user_id = u.id and i.provider = 'email'
  )                                                                  as has_email_identity,
  m.status                                                           as member_status
from auth.users u
join public.members m on lower(m.email) = lower(u.email)
where lower(u.email) in (
  {email_list}
)
order by m.role, m."ayurvedicId";
"""

    (ROOT / "sql").mkdir(exist_ok=True)
    (ROOT / "sql" / "set_all_member_passwords.sql").write_text(sql, encoding="utf-8")

    # ── Emit the credential table ───────────────────────────────────────────
    lines = [
        "# AyurTrace+ — Portal Login Credentials",
        "",
        "Generated by `scripts/generate_member_passwords.py`.",
        "Apply with `sql/set_all_member_passwords.sql` (Supabase → SQL Editor).",
        "",
        "Sign in at the portal with **Role + Ayurvedic ID + Email + Password**.",
        "",
        "> Shared demo passwords. Replace them before this handles real accounts.",
        "",
    ]

    for role in sorted({m["role"] for m in winners}):
        rows = [m for m in winners if m["role"] == role]
        lines += [
            f"## {role} ({len(rows)})",
            "",
            "| Ayurvedic ID | Organisation | Email | Password | Status |",
            "|---|---|---|---|---|",
        ]
        for m in sorted(rows, key=lambda r: r["_password"]):
            org = (m.get("organizationName") or m.get("name") or "").replace("|", "\\|")
            lines.append(
                f"| `{m['ayurvedicId']}` | {org} | {m['email']} | `{m['_password']}` | {m['status']} |"
            )
        lines.append("")

    if skipped:
        lines += [
            "## Excluded — duplicate email addresses",
            "",
            "`auth.users.email` is unique, so only one member per address can hold a",
            "login. These rows share an address with the member named below and get",
            "no credential. They also break sign-in for the winning row until",
            "resolved, because the member lookup matches two records.",
            "",
            "| Ayurvedic ID | Role | Email | Status | Reason |",
            "|---|---|---|---|---|",
        ]
        for m in skipped:
            lines.append(
                f"| `{m['ayurvedicId']}` | {m['role']} | {m['email']} | {m['status']} | {m['_reason']} |"
            )
        lines.append("")

    (ROOT / "CREDENTIALS.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"members read     : {len(members)}")
    print(f"credentials made : {len(winners)}")
    print(f"skipped (dupes)  : {len(skipped)}")
    print("wrote            : sql/set_all_member_passwords.sql")
    print("wrote            : CREDENTIALS.md")


if __name__ == "__main__":
    main()
